Repository Learning-Is-Vital-In-Development/24-software-architecture-101-2, pull requests merged in 2024-01, with the labels that each got.

#3 Update README.md
  README.md
Labels: size/XS

#4 add folders
  ch01/.placeholder
  ch02/.placeholder
  ch03/.placeholder
  ch04/.placeholder
  ch05/.placeholder
  ch06/.placeholder
  ch07/.placeholder
  ch08/.placeholder
  ch09/.placeholder
  ch10/.placeholder
  ch11/.placeholder
  ch12/.placeholder
  ch13/.placeholder
  ch14/.placeholder
  ch15/.placeholder
  ch16/.placeholder
  ch17/.placeholder
  ch18/.placeholder
  ch19/.placeholder
  ch20/.placeholder
  ch21/.placeholder
  ch22/.placeholder
  ch23/.placeholder
  ch24/.placeholder
Labels: size/XS

#12 chapter1, chapter2
  ch01/jieun.md
  ch02/jieun.md
Labels: size/XS

#11 시준 1주차 ch1, ch2
  ch01/서론.md
  ch02/아키텍처-사고.md
Labels: size/M

#10 수민 1주차 ch1, ch2
  ch01/sumin.md
  ch02/sumin.md
Labels: size/M

#9 태권 1주차 ch1, ch2
  ch01/taekwon.md
  ch02/taekwon.md
Labels: size/L

#8 준호 1주차 - 챕터 01,02
  ch01/joonholee.md
  ch02/joonholee.md
Labels: size/L

#7 예진 1주차 - 챕터 01,02
  ch01/yejin.md
  ch02/yejin.md
Labels: size/M

#6 재권 1주차 ch1, ch2
  ch01/jaekwon.md
  ch01/jaekwon/image1.jpeg
  ch01/jaekwon/image2.jpeg
  ch01/jaekwon/image3.jpeg
  ch01/jaekwon/image4.jpeg
  ch02/jaekwon.md
  ch02/jaekwon/image5.jpeg
  ch02/jaekwon/image6.jpeg
Labels: size/L

#5 원종 1주차 ch1, ch2
  ch01/wonjong.md
  ch01/wonjong/1-1.jpeg
  ch01/wonjong/1-2.jpeg
  ch01/wonjong/1-3.jpeg
  ch01/wonjong/1-4.jpeg
  ch01/wonjong/1-5.jpeg
  ch02/wonjong.md
  ch02/wonjong/2-1.jpeg
  ch02/wonjong/2-2.jpeg
  ch02/wonjong/2-3.jpeg
  ch02/wonjong/2-4.jpeg
Labels: size/L

#19 2주차 chapter 3, 4, 5
  ch01/jieun.md
  ch02/jieun.md
  ch03/jieun.md
  ch04/jieun.md
  ch05/jieun.md
Labels: size/L

#18 태권 2주차 ch3, ch4, ch5
  ch03/taekwon.md
  ch04/taekwon.md
  ch05/taekwon.md
Labels: size/L

#17 수민 2주차 ch.3,4,5
  ch03/sumin.md
  ch04/sumin.md
  ch05/sumin.md
Labels: size/L

#15 예진 3주차 - ch3, ch4, ch5
  ch03/yejin.md
  ch04/yejin.md
  ch05/yejin.md
Labels: size/L

#14 재권 2주차 ch3, ch4, ch5
  ch03/jaekwon.md
  ch04/jaekwon.md
  ch05/jaekwon.md
Labels: size/L

#26 정예진 6,7장
  ch06/yejin.md
  ch07/yejin.md
Labels: size/M

#24 엄태권 3주차 ch6, ch7
  ch06/taekwon.md
  ch07/taekwon.md
Labels: size/L

#23 이준호 3주차 6, 7과 요약
  ch06/image.jpeg
  ch06/joonholee.md
  ch07/image2.jpeg
  ch07/joonholee.md
Labels: size/L

#22 유수민 3주차 6,7장
  ch06/sumin.md
  ch07/sumin.md
Labels: size/M

#21 원종 3주차 Ch6, Ch7
  ch06/wonjong.md
  ch06/wonjong/6_1.jpeg
  ch06/wonjong/6_2.jpeg
  ch06/wonjong/6_3.jpeg
  ch07/wonjong.md
Labels: size/L

#20 재권 3주차 ch6, ch7
  ch06/jaekwon.md
  ch07/jaekwon.md
Labels: size/L
